services:
  lamebeats-db:
    image: postgres:17
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    container_name: lamebeats-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 10s
      interval: 5s
      retries: 5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lamebeats-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://35.209.62.223/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      lamebeats-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lamebeats-frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://35.209.62.223/api
      - PUBLIC_URL=http://35.209.62.223
    restart: unless-stopped

# Network configuration
networks:
  default:
    name: app-network
