services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lamebeats-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# Network configuration (for future frontend integration)
networks:
  default:
    name: app-network